server:
  default:
    appVersion: 1.0.0
    port: 5001
    readTimeout: 5
    writeTimeout: 5
    maxHeaderBytes: 1048576
    allowOrigins: "*"
    enableSecure: true
    securePort: 5002
    certFile: "${CERT_FILE_PATH}"
    keyFile: "${KEY_FILE_PATH}"
  grpc:
    port: 5003
    enableSecure: true
    securePort: 5004
    certFile: "${CERT_FILE_PATH}"
    keyFile: "${KEY_FILE_PATH}"

logger:
  level: info

cache:
  cap: 128
  cleanupInterval: 60