server:
  default:
    appVersion: 1.0.0
    port: 5001
    readTimeout: 5
    writeTimeout: 5
    maxHeaderBytes: 1048576
    allowOrigins: "*"
  grpc:
    port: 5002

logger:
  level: info

cache:
  cap: 128
  cleanupInterval: 60