server:
  default:
    appVersion: 1.0.0
    port: 5001
    readTimeout: 5
    writeTimeout: 5
    maxHeaderBytes: 1048576
    allowOrigins: "*"
    enableSecure: true
    securePort: 5002
    certFile: "certs/server.crt"
    keyFile: "certs/server.key"
  grpc:
    port: 5003
    enableSecure: true
    securePort: 5004
    certFile: "certs/server.crt"
    keyFile: "certs/server.key"

logger:
  level: info

cache:
  initCapacity: 128
  maxCapacity: 1024
  cleanupInterval: 60
  shrink:
    utilizationThreshold: 0.75
